apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: conntrack-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: conntrack-metrics
  template:
    metadata:
      labels:
        name: conntrack-metrics
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '9000'
    spec:
      containers:
        - command:
            - conntrack-metrics
            - -svc-subnet=10.96.0.0/16
            - -exclude-subnet=10.96.0.0/24
            - -node-name=$(NODE_NAME)
            - -metrics-bind-address=0.0.0.0:9000
            - -summary-timeout=30
#            - -print-events
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: quay.io/npinaeva/conntrack-metrics:v1
          imagePullPolicy: Always
          name: conntrack-metrics
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 500m
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
