apiVersion: v1
kind: Pod
metadata:
  name: client-{{.Replica}}
  labels:
    app: client
spec:
  enableServiceLinks: false
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: client
  containers:
  - name: client
    image: k8s.gcr.io/e2e-test-images/agnhost:2.39
{{- $svcIdx := mod .Replica .services}}
{{- if gt .services .clients }}
  {{- $svcIdx = sub (mul (div .services .clients) .Replica) 1 }}
{{- end}}
{{- $thirdOct := add (div $svcIdx 250) 1 }}
{{- $fourthOct := add (mod $svcIdx 250) 1 }}
    command: ["iperf", "-c", "10.96.{{$thirdOct}}.{{$fourthOct}}", "-p", "80", "-i", "1"]
  restartPolicy: Never
