apiVersion: v1
kind: Service
metadata:
  name: test-service-{{.Replica}}
spec:
  type: ClusterIP
{{- $svcIdx := sub .Replica 1 }}
{{- $thirdOct := add (div $svcIdx 250) 1 }}
{{- $fourthOct := add (mod $svcIdx 250) 1 }}
  clusterIP: 10.96.{{$thirdOct}}.{{$fourthOct}}
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
